export const LENDING_POOL_ABI = [
  {
    inputs: [{ internalType: "address", name: "target", type: "address" }],
    name: "AddressEmptyCode",
    type: "error",
  },
  { inputs: [], name: "AddressZero", type: "error" },
  { inputs: [], name: "AmountZero", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "implementation", type: "address" },
    ],
    name: "ERC1967InvalidImplementation",
    type: "error",
  },
  { inputs: [], name: "ERC1967NonPayable", type: "error" },
  { inputs: [], name: "FailedCall", type: "error" },
  { inputs: [], name: "InsufficientBalance", type: "error" },
  { inputs: [], name: "InsufficientLiquidityInLendingPool", type: "error" },
  { inputs: [], name: "InvalidInitialization", type: "error" },
  { inputs: [], name: "InvalidLendingPoolConfig", type: "error" },
  {
    inputs: [
      {
        components: [
          { internalType: "uint256", name: "tokenId", type: "uint256" },
          { internalType: "address", name: "protocol", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "uint256", name: "tokenAmount", type: "uint256" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "bytes", name: "data", type: "bytes" },
        ],
        internalType: "struct IPositionsRelayer.PositionsCollateralRequest",
        name: "collateralRequest",
        type: "tuple",
      },
    ],
    name: "InvalidRequest",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "requestId", type: "bytes32" }],
    name: "InvalidRequestId",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "newReserveFactor", type: "uint256" },
    ],
    name: "InvalidReserveFactor",
    type: "error",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "uint256", name: "totalLent", type: "uint256" },
          { internalType: "uint256", name: "totalBorrowed", type: "uint256" },
          { internalType: "uint256", name: "supplyIndex", type: "uint256" },
          { internalType: "uint256", name: "borrowIndex", type: "uint256" },
          {
            components: [
              { internalType: "uint256", name: "baseRate", type: "uint256" },
              { internalType: "uint256", name: "slope1", type: "uint256" },
              { internalType: "uint256", name: "slope2", type: "uint256" },
              {
                internalType: "uint256",
                name: "optimalUtilization",
                type: "uint256",
              },
            ],
            internalType: "struct PositionsLendingPool.InterestRateModel",
            name: "interestRateModel",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "lastAccrualTimestamp",
            type: "uint256",
          },
        ],
        internalType: "struct PositionsLendingPool.PoolData",
        name: "lendingPoolData",
        type: "tuple",
      },
    ],
    name: "LendingPoolDoesNotExist",
    type: "error",
  },
  { inputs: [], name: "NotInitializing", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "caller", type: "address" },
      { internalType: "address", name: "positionsRelayer", type: "address" },
    ],
    name: "NotPositionsRelayer",
    type: "error",
  },
  { inputs: [], name: "NotRelayer", type: "error" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "requestId", type: "bytes32" }],
    name: "RequestAlreadyFulfilled",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  { inputs: [], name: "UUPSUnauthorizedCallContext", type: "error" },
  {
    inputs: [{ internalType: "bytes32", name: "slot", type: "bytes32" }],
    name: "UUPSUnsupportedProxiableUUID",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "BorrowRequest",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "BorrowRequestFulfilled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        components: [
          { internalType: "uint256", name: "totalLent", type: "uint256" },
          { internalType: "uint256", name: "totalBorrowed", type: "uint256" },
          { internalType: "uint256", name: "supplyIndex", type: "uint256" },
          { internalType: "uint256", name: "borrowIndex", type: "uint256" },
          {
            components: [
              { internalType: "uint256", name: "baseRate", type: "uint256" },
              { internalType: "uint256", name: "slope1", type: "uint256" },
              { internalType: "uint256", name: "slope2", type: "uint256" },
              {
                internalType: "uint256",
                name: "optimalUtilization",
                type: "uint256",
              },
            ],
            internalType: "struct PositionsLendingPool.InterestRateModel",
            name: "interestRateModel",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "lastAccrualTimestamp",
            type: "uint256",
          },
        ],
        indexed: true,
        internalType: "struct PositionsLendingPool.PoolData",
        name: "lendingPoolData",
        type: "tuple",
      },
    ],
    name: "LendingPoolCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        components: [
          { internalType: "uint256", name: "baseRate", type: "uint256" },
          { internalType: "uint256", name: "slope1", type: "uint256" },
          { internalType: "uint256", name: "slope2", type: "uint256" },
          {
            internalType: "uint256",
            name: "optimalUtilization",
            type: "uint256",
          },
        ],
        indexed: true,
        internalType: "struct PositionsLendingPool.InterestRateModel",
        name: "interestRateModel",
        type: "tuple",
      },
    ],
    name: "LendingPoolInterestRateModelUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newOracle",
        type: "address",
      },
    ],
    name: "OracleSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newPositionsRelayer",
        type: "address",
      },
    ],
    name: "PositionsRelayerSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "by", type: "address" },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Repay",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "newReserveFactor",
        type: "uint256",
      },
    ],
    name: "ReserveFactorUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "onBehalfOf",
        type: "address",
      },
    ],
    name: "Supply",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newTreasury",
        type: "address",
      },
    ],
    name: "TreasurySet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "Upgraded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "by", type: "address" },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "interest",
        type: "uint256",
      },
      { indexed: false, internalType: "address", name: "to", type: "address" },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    inputs: [],
    name: "UPGRADE_INTERFACE_VERSION",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_asset", type: "address" }],
    name: "accrueInterest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "uint256", name: "tokenId", type: "uint256" },
          { internalType: "address", name: "protocol", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "uint256", name: "tokenAmount", type: "uint256" },
          { internalType: "uint256", name: "deadline", type: "uint256" },
          { internalType: "bytes", name: "data", type: "bytes" },
        ],
        internalType: "struct IPositionsRelayer.PositionsCollateralRequest",
        name: "_collateralRequest",
        type: "tuple",
      },
      { internalType: "bytes", name: "_signature", type: "bytes" },
    ],
    name: "borrowRequest",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_asset", type: "address" },
      {
        components: [
          { internalType: "uint256", name: "baseRate", type: "uint256" },
          { internalType: "uint256", name: "slope1", type: "uint256" },
          { internalType: "uint256", name: "slope2", type: "uint256" },
          {
            internalType: "uint256",
            name: "optimalUtilization",
            type: "uint256",
          },
        ],
        internalType: "struct PositionsLendingPool.InterestRateModel",
        name: "_interestRateModel",
        type: "tuple",
      },
    ],
    name: "createLendingPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_requestId", type: "bytes32" }],
    name: "fullfillCollateralRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_asset", type: "address" },
      { internalType: "address", name: "_lender", type: "address" },
    ],
    name: "getAccruedLenderInterest",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_supplier", type: "address" }],
    name: "getBalanceWithInterestAccrossAllAssets",
    outputs: [
      {
        components: [
          { internalType: "address", name: "asset", type: "address" },
          {
            internalType: "uint256",
            name: "balanceWithInterest",
            type: "uint256",
          },
        ],
        internalType: "struct PositionsLendingPool.SupplierData[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
      { internalType: "address", name: "_asset", type: "address" },
    ],
    name: "getBorrowRequestIds",
    outputs: [{ internalType: "bytes32[]", name: "", type: "bytes32[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_asset", type: "address" }],
    name: "getCurrentSupplyAndBorrowIndex",
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_asset", type: "address" }],
    name: "getReserveData",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "totalLiquidity", type: "uint256" },
          {
            internalType: "uint256",
            name: "availableLiquidity",
            type: "uint256",
          },
          { internalType: "uint256", name: "totalBorrows", type: "uint256" },
          { internalType: "uint256", name: "reserveFactor", type: "uint256" },
          { internalType: "uint256", name: "baseRate", type: "uint256" },
          { internalType: "uint256", name: "slope1", type: "uint256" },
          { internalType: "uint256", name: "slope2", type: "uint256" },
          {
            internalType: "uint256",
            name: "optimalUtilization",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastUpdateTimestamp",
            type: "uint256",
          },
          { internalType: "uint256", name: "supplyIndex", type: "uint256" },
          { internalType: "uint256", name: "borrowIndex", type: "uint256" },
          { internalType: "uint256", name: "supplyRate", type: "uint256" },
          { internalType: "uint256", name: "borrowRate", type: "uint256" },
          { internalType: "uint256", name: "utilization", type: "uint256" },
        ],
        internalType: "struct PositionsLendingPool.ReserveData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSupportedAssets",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_asset", type: "address" },
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
    ],
    name: "getborrowerDebt",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_admin", type: "address" },
      { internalType: "address", name: "_positionsRelayer", type: "address" },
      { internalType: "address", name: "_priceOracle", type: "address" },
      {
        internalType: "uint256",
        name: "_initialReserveFactor",
        type: "uint256",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "oracle",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "asset", type: "address" }],
    name: "poolData",
    outputs: [
      { internalType: "uint256", name: "totalLent", type: "uint256" },
      { internalType: "uint256", name: "totalBorrowed", type: "uint256" },
      { internalType: "uint256", name: "supplyIndex", type: "uint256" },
      { internalType: "uint256", name: "borrowIndex", type: "uint256" },
      {
        components: [
          { internalType: "uint256", name: "baseRate", type: "uint256" },
          { internalType: "uint256", name: "slope1", type: "uint256" },
          { internalType: "uint256", name: "slope2", type: "uint256" },
          {
            internalType: "uint256",
            name: "optimalUtilization",
            type: "uint256",
          },
        ],
        internalType: "struct PositionsLendingPool.InterestRateModel",
        name: "interestRateModel",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "lastAccrualTimestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "positionsRelayer",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proxiableUUID",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_asset", type: "address" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
    ],
    name: "repayDebt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "reserveFactor",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_newOracle", type: "address" }],
    name: "setOracle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_newRelayer", type: "address" }],
    name: "setPositionsRelayer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_newTreasury", type: "address" },
    ],
    name: "setTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_asset", type: "address" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "address", name: "_for", type: "address" },
    ],
    name: "supply",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "address", name: "asset", type: "address" },
    ],
    name: "tokenIdToAssetToBorrowInfo",
    outputs: [
      { internalType: "uint256", name: "borrowedAmount", type: "uint256" },
      { internalType: "uint256", name: "borrowIndexSnapshot", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "treasury",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_asset", type: "address" },
      {
        components: [
          { internalType: "uint256", name: "baseRate", type: "uint256" },
          { internalType: "uint256", name: "slope1", type: "uint256" },
          { internalType: "uint256", name: "slope2", type: "uint256" },
          {
            internalType: "uint256",
            name: "optimalUtilization",
            type: "uint256",
          },
        ],
        internalType: "struct PositionsLendingPool.InterestRateModel",
        name: "_interestRateModel",
        type: "tuple",
      },
    ],
    name: "updateLendingPoolInterestRateModel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_newReserveFactor", type: "uint256" },
    ],
    name: "updateReserveFactor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "newImplementation", type: "address" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "upgradeToAndCall",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "address", name: "asset", type: "address" },
    ],
    name: "userToAssetToLendingInfo",
    outputs: [
      { internalType: "uint256", name: "depositAmount", type: "uint256" },
      { internalType: "uint256", name: "supplyIndexSnapshot", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_tokenId", type: "uint256" }],
    name: "utilization",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_asset", type: "address" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "address", name: "_to", type: "address" },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
