version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  positions-producer:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=transactions
      - BERACHAIN_RPC_URL=${BERACHAIN_RPC_URL:-https://artio.rpc.berachain.com}
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  redis-data:
